package codegen

import (
	"fmt"
	"io"
	"strings"
)

var headerTemplate = strings.TrimSpace(`
//go:build %s && !windows

// Code generated by directcgo. DO NOT EDIT.
// %s

#include "go_asm.h"
#include "textflag.h"
#include "funcdata.h"
`) + "\n\n"

type headerVars struct {
	arch    string
	fullcmd string
}

func (v *headerVars) Format(w io.Writer) error {
	_, err := fmt.Fprintf(w, headerTemplate, v.arch, v.fullcmd)
	return err
}
