//go:build arm64 && !windows

// Code generated by directcgo. DO NOT EDIT.
// directcgo -arch=amd64,arm64 ./testsuite/binding

#include "go_asm.h"
#include "textflag.h"
#include "funcdata.h"

// PassIntegers func(fn unsafe.Pointer, i32 int32, i64 int64, i16 int16, i8 int8)
TEXT ·PassIntegers(SB), $65536-27
	MOVD    fn+0(FP), R9
	MOVW    i32+8(FP), R0
	MOVD    i64+16(FP), R1
	MOVH    i16+24(FP), R2
	MOVB    i8+26(FP), R3
	MOVD    $0xF51A4219, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0xF51A4219, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassUnsignedIntegers func(fn unsafe.Pointer, u32 uint32, u64 uint64, u8 uint8, u16 uint16)
TEXT ·PassUnsignedIntegers(SB), $65536-28
	MOVD    fn+0(FP), R9
	MOVWU   u32+8(FP), R0
	MOVD    u64+16(FP), R1
	MOVBU   u8+24(FP), R2
	MOVHU   u16+26(FP), R3
	MOVD    $0x4A36BCE, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x4A36BCE, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassFloats func(fn unsafe.Pointer, f32_0 float32, f64_0 float64, f64_1 float64, f32_1 float32)
TEXT ·PassFloats(SB), $65536-36
	MOVD    fn+0(FP), R9
	FMOVS   f32_0+8(FP), F0
	FMOVD   f64_0+16(FP), F1
	FMOVD   f64_1+24(FP), F2
	FMOVS   f32_1+32(FP), F3
	MOVD    $0xFB966F8A, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0xFB966F8A, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassMixedNumbers func(fn unsafe.Pointer, i8 int8, f32 float32, u32 uint32, f64 float64, i64 int64)
TEXT ·PassMixedNumbers(SB), $65536-40
	MOVD    fn+0(FP), R9
	MOVB    i8+8(FP), R0
	FMOVS   f32+12(FP), F0
	MOVWU   u32+16(FP), R1
	FMOVD   f64+24(FP), F1
	MOVD    i64+32(FP), R2
	MOVD    $0x61A92597, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x61A92597, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// ReturnUInt8 func(fn unsafe.Pointer) uint8
TEXT ·ReturnUInt8(SB), $65536-9
	MOVD    fn+0(FP), R9
	MOVD    $0x8A5FE07A, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x8A5FE07A, R11
	CMP     R10, R11
	BNE     overflow
	MOVBU   R0, ret+8(FP)
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// ReturnInt8 func(fn unsafe.Pointer) int8
TEXT ·ReturnInt8(SB), $65536-9
	MOVD    fn+0(FP), R9
	MOVD    $0xC188B80B, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0xC188B80B, R11
	CMP     R10, R11
	BNE     overflow
	MOVB    R0, ret+8(FP)
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// ReturnUInt32 func(fn unsafe.Pointer) uint32
TEXT ·ReturnUInt32(SB), $65536-12
	MOVD    fn+0(FP), R9
	MOVD    $0x2414C9BE, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x2414C9BE, R11
	CMP     R10, R11
	BNE     overflow
	MOVWU   R0, ret+8(FP)
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// ReturnInt32 func(fn unsafe.Pointer) int32
TEXT ·ReturnInt32(SB), $65536-12
	MOVD    fn+0(FP), R9
	MOVD    $0x7EE47F, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x7EE47F, R11
	CMP     R10, R11
	BNE     overflow
	MOVW    R0, ret+8(FP)
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// ReturnUInt64 func(fn unsafe.Pointer) uint64
TEXT ·ReturnUInt64(SB), $65536-16
	MOVD    fn+0(FP), R9
	MOVD    $0x87B7B8F8, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x87B7B8F8, R11
	CMP     R10, R11
	BNE     overflow
	MOVD    R0, ret+8(FP)
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// ReturnInt64 func(fn unsafe.Pointer) int64
TEXT ·ReturnInt64(SB), $65536-16
	MOVD    fn+0(FP), R9
	MOVD    $0xA760BDE5, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0xA760BDE5, R11
	CMP     R10, R11
	BNE     overflow
	MOVD    R0, ret+8(FP)
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// ReturnFloat func(fn unsafe.Pointer) float32
TEXT ·ReturnFloat(SB), $65536-12
	MOVD    fn+0(FP), R9
	MOVD    $0x89131C30, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x89131C30, R11
	CMP     R10, R11
	BNE     overflow
	FMOVS   F0, ret+8(FP)
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// ReturnDouble func(fn unsafe.Pointer) float64
TEXT ·ReturnDouble(SB), $65536-16
	MOVD    fn+0(FP), R9
	MOVD    $0x47EA2CF, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x47EA2CF, R11
	CMP     R10, R11
	BNE     overflow
	FMOVD   F0, ret+8(FP)
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassSmallStructSameIntegers func(fn unsafe.Pointer, s SmallStructSameIntegers)
TEXT ·PassSmallStructSameIntegers(SB), $65536-16
	MOVD    fn+0(FP), R9
	MOVD    s+8(FP), R0
	MOVD    $0x8B8B10C2, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x8B8B10C2, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassSmallStructMixedIntegers func(fn unsafe.Pointer, s SmallStructMixedIntegers)
TEXT ·PassSmallStructMixedIntegers(SB), $65536-26
	MOVD    fn+0(FP), R9
	MOVD    s+8(FP), R0
	MOVD    s+16(FP), R1
	MOVD    $0x879EB4D2, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x879EB4D2, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassSmallStructSameFloats func(fn unsafe.Pointer, s SmallStructSameFloats)
TEXT ·PassSmallStructSameFloats(SB), $65536-28
	MOVD    fn+0(FP), R9
	FMOVS   s_0+8(FP), F0
	FMOVS   s_1+12(FP), F1
	FMOVS   s_2+16(FP), F2
	MOVD    $0xA8292C92, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0xA8292C92, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassSmallStructMixedFloats func(fn unsafe.Pointer, s SmallStructMixedFloats)
TEXT ·PassSmallStructMixedFloats(SB), $65536-32
	MOVD    fn+0(FP), R9
	MOVD    s+8(FP), R0
	MOVD    s+16(FP), R1
	MOVD    $0x80DD353C, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0x80DD353C, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassSmallStructMixedNumbers func(fn unsafe.Pointer, s SmallStructMixedNumbers)
TEXT ·PassSmallStructMixedNumbers(SB), $65536-30
	MOVD    fn+0(FP), R9
	MOVD    s+8(FP), R0
	MOVD    s+16(FP), R1
	MOVD    $0xF126DC84, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0xF126DC84, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassSmallStructNested func(fn unsafe.Pointer, s SmallStructOuter)
TEXT ·PassSmallStructNested(SB), $65536-16
	MOVD    fn+0(FP), R9
	MOVD    s+8(FP), R0
	MOVD    $0xDA593CF1, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0xDA593CF1, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET

// PassSmallStructWithArray func(fn unsafe.Pointer, s SmallStructWithArray)
TEXT ·PassSmallStructWithArray(SB), $65536-32
	MOVD    fn+0(FP), R9
	MOVD    s+8(FP), R0
	MOVD    s+16(FP), R1
	MOVD    $0xEAB8C376, R10
	MOVD    R10, 8(RSP)
	MOVD    RSP, R20
	MOVD    $65536, R10
	ADD     R10, RSP
	MOVD    RSP, R10
	AND     $~15, R10, RSP
	BL      (R9)
	MOVD    R20, RSP
	MOVD    8(RSP), R10
	MOVD    $0xEAB8C376, R11
	CMP     R10, R11
	BNE     overflow
	RET
overflow:
	CALL    runtime·abort(SB)
	RET
